### ISSUE TITLE
作業中

### ISSUE THREAD

**Issue by Nenetti** [rionehome/navigation#2]
# 概要
現在マッピングのセーブとロードの簡易化を行っています

# 作業ブランチ
nenecchi_dev

**Comment by HiroRittsu** [comment]
rosrun は実行した場所がカレントディレクトリになるから、必ずしもホームにyamlとか置かなくてもええでー

**Comment by Nenetti** [comment]
roslaunchでやっちゃうと.rosがカレントになるんで、cdコマンドをrosrun前に挟んであげないとダメなんですよ
