### ISSUE TITLE
navigationパッケージの削除

### ISSUE THREAD

**Issue by HiroRittsu** [rionehome/navigation#4]
仕様変更に伴い、削除する予定

**Comment by Nenetti** [comment]
ん？消すん？
どこに機能を移すん？

**Comment by HiroRittsu** [comment]
navigation/navigationのみ削除で、mappingとlocationは必要なのでこのまま残す、という一応予定。

もともとnavigationで回転角度、直進距離、座標指定、そして場所名の４つを受け付けて、パッケージの中で計算した後、move_baseに投げるほうがいいんじゃないかと思ってたんだけど。

そもそもhuman_detectionのときとかで使った直進、ダイレクトに座標でやった方が確実じゃんって気がついてまず要らなくなった。んでさらに回転とか座標指定とかはmove_baseに直接投げるのとほとんど変わんないじゃんとなった。場所名も、locationに直接問い合わせて、座標をぶん投げたほうがきれいだなとなり、今に至る。

**Comment by Nenetti** [comment]
実質navigationとlocationを一部統合
それ以外は各パッケージ内で呼び出すってことやな

そのほうがいいならそれでいいんじゃない？

**Comment by HiroRittsu** [comment]
統合はしないよ。navigation/navigationだけ削除。
location情報は自分で読みにいく形にする。

デバッグとかでnavigation/navigation必要なら残すけど。

**Comment by Nenetti** [comment]
なんで読みにくい形にするのかは知らんが、別に削除していいぞ
必要だったら後からcheckoutで戻せばいいだけやし
